import {useState} from 'react'

let nextColas = n => 3*(n % 2 ?  n + 1 : n >> 1)
let nextColaz = n => n % 2 ? 3*n + 1 : n >> 1

let initialize = n => {
	let data = {
		colaz : [n],
		colas : [3*n],
		max : -1
	}

	for (let count=0; count < 101; count++ ){
		let clz = nextColaz(data.colaz[0])
		let cls = nextColas(clz)

		data.colaz.unshift(clz)
		data.colas.unshift(cls)
		data.max = Math.max(Math.max(data.max, clz), cls)
	}

	return data

}

const barStyle = {
	width: '900px',
	position: 'absolute'
}

const Content = props => {
	let {Component,selection, state,asset, style, onUpdate} = props

	let data = initialize(27)

	return  <div style={style}>
			<div style={{width: '80%'}}>
				<p>Here I present a proof of the Collatz conjecture, which is believed to be true</p>

				<p>
					Consider the sequence generated by Colas <br/>
					Observe that I assume natural numbers.
				</p>

				<img style={{height: '50px'}} src={asset.Colas} alt='Colas sequence' />

				<p>and the sequence generated by Collatz</p>


				<img style={{height: '50px'}} src={asset.Colaz} alt='Collaz sequence' />

				<p>Now assume that z(x) tends to infinity.</p>
				<p>It is easy to prove, at least, for any natural number, the following inequality, which I leave to you as exercise ...</p>

				<img style={{height: '30px'}} src={asset.Inequality} alt='Colas inequality' />

				<p>
					But this inequality is a contradiction, also establishing an upper bound for z(x)<br/>

					Since s(x) converges to 1 (easy proof using induction), 3*s(x) will converge to 3. This leads to the conclusion that z(x),
					the Collatz sequence, converges to 1, which is already known for x less than 3.
				</p>
				<p>
					One could argue that z(x), after some large index i, stays on a constant K larger than 1. <br/>
					In this case we can substitute the inequality by z(x) &lt; 3*s(K + i). Eventually, 3*s( K + i ) will converge to 3 as i goes to infinity.
				</p>

				<p>This is true in general, if 3 is substituted by a prime number greater than 2</p>

				<p>The chart is giving a hint of what is going on for 27 as the initial number</p>
				<p>The red bars show z(x) ) and the white bars show  3*s(z(x)), using a logarithmic scale</p>

				<div>
					<div style={barStyle}>
						<Component.Bars
							data={data.colas.map(v => Math.log(v))}
							width='600'
							height='300'
							max = {Math.log(data.max)}
							fill = 'white'
						/>
					</div>

					<div style={barStyle}>
						<Component.Bars
							data={data.colaz.map(v => Math.log(v))}
							width='600'
							height='300'
							max = {Math.log(data.max)}
							fill = 'red'
						/>
					</div>
				</div>

			</div>
		</div>
}

export {Content}
